# Generated by Django 5.2 on 2025-04-28 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mc_uuid',
        ),
    ]
