# Generated by Django 5.2 on 2025-05-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0002_remove_user_mc_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mc_username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
