# Generated by Django 5.2 on 2025-06-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_account', '0003_alter_user_mc_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
