# Generated by Django 5.2.3 on 2025-07-06 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0004_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
