# Generated by Django 5.2 on 2025-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account', '0006_user_is_online_user_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manual_status',
            field=models.CharField(blank=True, choices=[('', 'Auto'), ('idle', 'Idle'), ('invisible', 'Invisible')], default='', max_length=20),
        ),
    ]
