version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: redmarket_web:latest
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - /app/.venv
    ports:
      - "8000:8000"
    networks:
      - general
    depends_on:
      - db

  db:
    build:
      context: ./docker/mysql
      args:
        - 'MYSQL_VERSION=${MYSQL_VERSION}'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'TZ=UTC'
    ports:
      - "3306:3306"
    networks:
      - general
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - general
    volumes:
      - redis_data:/data

  celery:
    image: redmarket_web:latest
    env_file:
      - .env
    volumes:
      - .:/app:cached
    depends_on:
      - web
      - redis
    entrypoint: [ "poetry", "run" ]
    command: [ "celery", "-A", "redmarket", "worker", "-l", "info" ]
    networks:
      - general

  celery-beat:
    image: redmarket_web:latest
    env_file:
      - .env
    volumes:
      - .:/app:cached
    depends_on:
      - web
      - redis
    entrypoint: [ "poetry", "run" ]
    command: [ "celery", "-A", "redmarket", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler" ]
    networks:
      - general

volumes:
  mysql_data:
  redis_data:

networks:
  general:
    driver: bridge
