version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - /app/.venv
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    build:
      context: ./docker/mysql
      args:
        - 'MYSQL_VERSION=${MYSQL_VERSION}'
    environment:
      - 'MYSQL_DATABASE=${DB_NAME}'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'
      - 'TZ=UTC'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
