# Generated by Django 5.2 on 2025-05-21 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_item.itemtype')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_item.material')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEnchantment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('enchantment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_item.enchantment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_order.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='enchantments',
            field=models.ManyToManyField(through='app_order.OrderEnchantment', to='app_item.enchantment'),
        ),
    ]
