# Generated by Django 5.2 on 2025-05-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_order', '0002_order_created_by_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
