# Generated by Django 5.2 on 2025-05-31 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0003_order_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
