# Generated by Django 5.2 on 2025-06-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_social', '0002_thread_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='thread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
